sonar.projectKey=DallasLaComb_ttb-label-verifier
sonar.organization=dallaslacomb

sonar.sources=backend/src,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.aws-sam/**,**/.angular/**,frontend/src/environments/**,frontend/src/main.ts

sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info,backend/coverage/lcov.info
