sonar.projectKey=DallasLaComb_ttb-label-verifier
sonar.organization=dallaslacomb

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.aws-sam/**,**/.angular/**
